<?php
/**
 * Admin – Message REST Controller (Refactored for JSON + Form support)
 *
 * Thin REST layer: parses WP_REST_Request, delegates to FormService,
 * logs every call for auditing. No direct DB access.
 *
 * @package ContactInbox\Admin
 * @since   1.6.1
 */

namespace ContactInbox\Admin\Controllers;

use ContactInbox\Core\FormService;
use ContactInbox\Core\Config;
use ContactInbox\Core\DB;
use ContactInbox\Core\Settings as CoreSettings;
use WP_Error;
use WP_REST_Request;

if (!defined('ABSPATH')) exit;

final class RestController {

    private static function ensure_enabled() {
        $settings = CoreSettings::get_settings();
        if (empty($settings['restapi_enable'])) {
            return new WP_Error(
                Config::ERR_REST_DISABLED,
                __('REST API service is disabled in plugin settings.', 'contact-inbox'),
                ['status' => 403]
            );
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Handlers (Route registration delegated to RestApiRoutes with proper permissions)
    // -------------------------------------------------------------------------
    public static function submit( \WP_REST_Request $request ) {
        // Ensure the controller is enabled
        $enabled = self::ensure_enabled();
        if ( $enabled instanceof \WP_Error ) {
            return $enabled;
        }

        // Extract incoming params and files
        $params = $request->get_json_params() ?? $request->get_body_params() ?? [];
        $files  = $request->get_file_params() ?? [];

        // FormService.submit() now handles EVERYTHING:
        // - Validation
        // - Duplicate detection
        // - Database save (atomic transaction)
        // - GDPR token generation
        // Returns: ['message_id' => int, 'payload' => array, 'gdpr_delete_link' => string]
        $form_result = \ContactInbox\Core\FormService::submit( $params, $files );
        if ( is_wp_error( $form_result ) ) {
            // Render failure template
            $failure_html = \ContactInbox\Core\TemplateLoader::render(
                CONTACTINBOX_PATH . 'templates/frontend/form-failure-message.php',
                [
                    'failure_message' => $form_result->get_error_message(),
                    'failure_tip'     => '',
                ]
            );
            return [
                'success' => false,
                'action'  => 'submit',
                'message' => $form_result->get_error_message(),
                'data'    => [ 'html' => $failure_html ],
                'timestamp' => time(),
            ];
        }

        // FormService already saved the message and generated GDPR token
        // Extract data from the result
        $message_id = $form_result['message_id'] ?? 0;
        $payload = $form_result['payload'] ?? [];
        $validated_files = $form_result['files'] ?? [];
        $delete_link = $form_result['gdpr_delete_link'] ?? '';

        // Trigger analytics and queue processing hooks
        // NOTE: This should only fire ONCE per submission
        if ( ! empty( $payload ) && $message_id > 0 ) {
            do_action( 'contactin_message_received', $message_id, $payload );
        }

        // Render success template (GDPR link already generated by FormService)
        $settings = get_option( Config::OPTION_SETTINGS, [] );
        
        $success_html = \ContactInbox\Core\TemplateLoader::render(
            CONTACTINBOX_PATH . 'templates/frontend/form-success-message.php',
            [
                'settings' => $settings,
                'delete_link' => $delete_link,
                'attachment' => $validated_files['attachment']['name'] ?? '',
                'masked_receipt' => '',
            ]
        );

        // Return success response
        return [
            'success'   => true,
            'action'    => 'submit',
            'id'        => $message_id,
            'message'   => __( 'Message received successfully', 'contact-inbox' ),
            'data'      => [ 'html' => $success_html ],
            'timestamp' => time(),
        ];
    }

    public static function list_messages(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $page = (int) $request->get_param('page') ?: 1;
        $perPage = (int) $request->get_param('per_page') ?: Config::INBOX_PER_PAGE;

        return FormService::list_messages(['page' => $page, 'per_page' => $perPage]);
    }

    public static function read(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $id = (int) $request->get_param('id');
        return FormService::read($id);
    }

    public static function update_status(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $params = $request->get_json_params() ?? $request->get_body_params() ?? [];
        $id     = (int) ($params['id'] ?? $request->get_param('id'));
        $status = (string) ($params['status'] ?? $request->get_param('status'));

        return FormService::update_status($id, $status);
    }

    public static function search_messages(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $q       = (string) $request->get_param('q');
        $page    = (int) $request->get_param('page') ?: 1;
        $perPage = (int) $request->get_param('per_page') ?: Config::INBOX_PER_PAGE;

        return FormService::search_messages($q, $page, $perPage);
    }

    public static function bulk_delete(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $params = $request->get_json_params() ?? $request->get_body_params() ?? [];
        $ids    = (array) ($params['ids'] ?? $request->get_param('ids'));

        return FormService::bulk_delete($ids);
    }

    public static function gdpr_request(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $params = $request->get_json_params() ?? $request->get_body_params() ?? [];
        return FormService::gdpr_request($params);
    }

    public static function gdpr_delete(WP_REST_Request $request) {
        $enabled = self::ensure_enabled();
        if ($enabled instanceof WP_Error) return $enabled;

        $token = (string) $request->get_param('token');
        return FormService::gdpr_delete($token);
    }

}
